import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GoogleOAuthProvider } from '@react-oauth/google';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import { Toaster } from 'react-hot-toast';

import { ReactQueryDevtools } from '@tanstack/react-query-devtools';

// import { QueryClient, QueryClientProvider } from '@tanstack/react-query'

import { Providers } from "@/QueryClientProvider";

// const queryClient = new QueryClient()

export const metadata: Metadata = {
  title: "X",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <GoogleOAuthProvider clientId="677107428141-nemjv35hj2kla7sb1dp0sokasl844nq8.apps.googleusercontent.com">
          <body className={inter.className}>{children}</body>
          <Toaster/>
          <ReactQueryDevtools />
        </GoogleOAuthProvider>
      </Providers>
    </html>
  );
}
